/**
 * The company's own cost codes (CSI-based), as supplied. Whole divisions are
 * the two-digit codes; the rest sit under them. Kept as given -- including
 * combined rows such as "06.20 & 06.22 & 06.26" and ranges like "09.60-09.69",
 * which the estimate uses for bundled scopes.
 */
export const COMPANY_COST_CODES: { code: string; name: string; description?: string }[] = [
  { code: '01', name: 'General Requirements' },
  { code: '01.33', name: 'Design' },
  { code: '01.41', name: 'Municipal Review & Fees' },
  { code: '01.51', name: 'Temporary Power' },
  { code: '01.52', name: 'Temp Toilet & Wash' },
  { code: '01.55', name: 'Materials Staging' },
  { code: '01.56', name: 'Tree Protection' },
  { code: '01.71', name: 'Mobilization' },
  { code: '02', name: 'Existing Conditions' },
  { code: '02.01', name: 'Site Protection' },
  { code: '02.03', name: 'Salvage and Recycle' },
  { code: '02.21', name: 'Boundary Survey' },
  { code: '02.41', name: 'Demolition', description: 'Demo, Salvage and Recycle, Site Protection' },
  { code: '03', name: 'Foundation Concrete' },
  { code: '03.11', name: 'Sub-Grade Basement' },
  { code: '03.30', name: 'Concrete Footing' },
  { code: '03.31', name: 'Concrete Piers' },
  { code: '03.35', name: 'Concrete Slabs' },
  { code: '04', name: 'Masonry' },
  { code: '05', name: 'Metals' },
  { code: '05.10', name: 'Structural Metal Frame' },
  { code: '05.52', name: 'Guardrail & Handrail', description: 'Metal, Wood, Glass' },
  { code: '06', name: 'Wood & Composites' },
  { code: '06.10', name: 'Structural Wood Frame' },
  { code: '06.20 & 06.22 & 06.26', name: 'Finish Carpentry, Millwork and Door & Window trim' },
  { code: '06.20', name: 'Finish Carpentry' },
  { code: '06.22', name: 'Millwork' },
  { code: '06.41', name: 'Cabinetry & Shelving' },
  { code: '06.26', name: 'Door & Window Trim' },
  { code: '07', name: 'Thermal & Moisture Protection' },
  { code: '07.12', name: 'Waterproofing' },
  { code: '07.21', name: 'Insulation' },
  { code: '07.30', name: 'Roofing' },
  { code: '07.31', name: 'Roofing - Asphalt Shingle' },
  { code: '07.32', name: 'Roofing - Tiles' },
  { code: '07.41', name: 'Roofing - Metal' },
  { code: '07.46', name: 'Exterior Siding' },
  { code: '07.54', name: 'Roofing - Membrane' },
  { code: '08', name: 'Openings - Exterior Doors, Windows, Skylights, and Hardware' },
  { code: '08.10', name: 'Doors - Interior' },
  { code: '08.13', name: 'Doors - Exterior' },
  { code: '08.30', name: 'Doors - Exterior Specialty' },
  { code: '08.50', name: 'Windows' },
  { code: '08.56', name: 'Specialty Windows' },
  { code: '08.60', name: 'Skylights' },
  { code: '08.70', name: 'Hardware' },
  { code: '09', name: 'Finishes' },
  { code: '09.20', name: 'Drywall & Finish' },
  { code: '09.20', name: 'Plaster and Gypsum Board (Drywall)' },
  { code: '09.24', name: 'Stucco' },
  { code: '09.29', name: 'Gypsum Board' },
  { code: '09.30', name: 'Flooring - Tile' },
  { code: '09.31', name: 'Tile - Backsplash & Shower' },
  { code: '09.60', name: 'Flooring - Wood' },
  { code: '09.60-09.69', name: 'Flooring' },
  { code: '09.90-09.97', name: 'Painting and Coating' },
  { code: '09.90', name: 'Paint - Exterior' },
  { code: '09.91', name: 'Paint - Interior' },
  { code: '09.97', name: 'Specialty Coating' },
  { code: '10', name: 'Specialties' },
  { code: '10.28', name: 'Toilet, Bath, and Laundry Accessories' },
  { code: '10.28', name: 'Glass Shower Enclosure' },
  { code: '10.57', name: 'Closet Systems' },
  { code: '11', name: 'Equipment' },
  { code: '11.30', name: 'Major Residential Appliances' },
  { code: '12', name: 'Furnishings' },
  { code: '12.36', name: 'Countertops' },
  { code: '12.40', name: 'Furnishings' },
  { code: '13', name: 'Special Construction' },
  { code: '13.11', name: 'Swimming Pools' },
  { code: '14', name: 'Conveying Equipment' },
  { code: '21', name: 'Fire Suppression' },
  { code: '21.40', name: 'Fire Suppression System' },
  { code: '22', name: 'Plumbing' },
  { code: '22.10', name: 'Plumbing Rough-in' },
  { code: '22.30', name: 'Plumbing Equipment' },
  { code: '22.41', name: 'Plumbing Fixture' },
  { code: '23', name: 'HVAC Systems' },
  { code: '23.30', name: 'HVAC Rough-in' },
  { code: '23.54', name: 'HVAC Equip' },
  { code: '23.', name: 'HVAC Finish' },
  { code: '25', name: 'Integrated Automation' },
  { code: '25.10', name: 'Data/COMM Rough-IN' },
  { code: '26', name: 'Electrical' },
  { code: '26.10', name: 'Electrical - Rough In' },
  { code: '26.50', name: 'Electrical - Fixtures' },
  { code: '27', name: 'Communications' },
  { code: '28', name: 'Electronic Safety and Security' },
  { code: '31', name: 'Earthwork' },
  { code: '31.10', name: 'Site Clearing' },
  { code: '31.22', name: 'Grading & Excavation' },
  { code: '32', name: 'Exterior Improvements' },
  { code: '32.12', name: 'Hardscape (on site)' },
  { code: '32.16', name: 'Hardscape (R.O.W.)' },
  { code: '32.31', name: 'Fences & Gates' },
  { code: '32.32', name: 'Retaining Walls' },
  { code: '32.80', name: 'Irrigation' },
  { code: '32.90', name: 'Landscape & Irrigation' },
  { code: '33', name: 'Utilities' },
  { code: '33.10 & 33.30 & 33.40', name: 'Utility - Water, Waste, Storm' },
  { code: '33.10', name: 'Utility - Water' },
  { code: '33.30', name: 'Utility - Waste Water' },
  { code: '33.40', name: 'Storm Water Management' },
  { code: '33.50 & 33.60', name: 'Utility - Gas and Electrical' },
  { code: '33.50', name: 'Utility - Gas' },
  { code: '33.60', name: 'Utility - Electrical' },
  { code: '34', name: 'Transportation' },
  { code: '48.14', name: 'Solar Energy Electrical Power Generation Equipment' },
  { code: '99999', name: 'Other (See Notes)' },
  { code: '00000', name: 'Not Used' },
];

/** Stable ids: a two-digit division keeps the id the original MasterFormat seed gave it (CSI-03), so existing references survive. */
export function costCodeId(code: string, name: string, taken: Set<string>) {
  const base = /^\d{2}$/.test(code) ? `CSI-${code}` : `CSI-${code.replace(/[^0-9A-Za-z]+/g, '_')}`;
  let id = base;
  for (let n = 2; taken.has(id); n++) id = `${base}-${n}`;
  taken.add(id);
  return id;
}
