import { IsString, IsOptional, IsNumber, IsArray } from 'class-validator';

/** ValidationPipe runs with `whitelist: true` -- every field must be declared here. */
export class CreateEmployeeDto {
  @IsString() @IsOptional() id?: string;
  @IsString() name: string;
  @IsString() @IsOptional() workerId?: string;
  @IsString() @IsOptional() fatherOrSpouseName?: string;
  @IsString() @IsOptional() nationalId?: string;
  @IsString() @IsOptional() dob?: string;
  @IsString() @IsOptional() gender?: string;
  @IsString() @IsOptional() phone?: string;
  @IsString() @IsOptional() email?: string;
  @IsString() @IsOptional() emergencyContactName?: string;
  @IsString() @IsOptional() emergencyContactPhone?: string;
  @IsString() @IsOptional() emergencyContactRelation?: string;
  @IsString() @IsOptional() permanentAddress?: string;
  @IsString() @IsOptional() currentAddress?: string;
  @IsString() @IsOptional() employmentType?: string;
  @IsString() @IsOptional() hireDate?: string;
  @IsString() @IsOptional() department?: string;
  @IsString() @IsOptional() designation?: string;
  @IsString() @IsOptional() jobTitle?: string;
  @IsString() @IsOptional() grade?: string;
  @IsString() @IsOptional() employmentStatus?: string;
  @IsString() @IsOptional() status?: string;
  @IsString() @IsOptional() supervisorId?: string | null;
  @IsString() @IsOptional() hrOfficerId?: string | null;
  @IsString() @IsOptional() userId?: string | null;
  @IsString() @IsOptional() payType?: string;
  @IsNumber() @IsOptional() payRate?: number;
  @IsString() @IsOptional() bankName?: string;
  @IsString() @IsOptional() bankAccount?: string;
  @IsString() @IsOptional() taxNumber?: string;
  @IsString() @IsOptional() bankRoutingNumber?: string;
  @IsString() @IsOptional() filingStatus?: string;
  @IsString() @IsOptional() taxState?: string;
  @IsString() @IsOptional() flsaStatus?: string;
  @IsString() @IsOptional() workersCompClass?: string;
  @IsString() @IsOptional() tradeId?: string | null;
  @IsString() @IsOptional() trade?: string;
  @IsString() @IsOptional() skillLevel?: string;
  @IsNumber() @IsOptional() yearsExperience?: number;
  @IsArray() @IsOptional() expertise?: string[];
  @IsArray() @IsOptional() equipmentCapabilities?: string[];
  @IsString() @IsOptional() contractorId?: string | null;
  @IsString() @IsOptional() siteAccessStatus?: string;
  @IsArray() @IsOptional() payComponents?: { componentId: string; value: number }[];
  @IsNumber() @IsOptional() overtimeRate?: number | null;
}
